version: "3.3"
# Указываем раздел со связанными сервисами

services:
  nginx:
    depends_on:
      - frontend
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      # Используем свой nginx конфиг, он заменит дефолтный в контейнере
      - ./nginx:/etc/nginx/conf.d
      # Монтируем папку с логами на хост машину для более удобного доступа
      - ./logs:/var/log/nginx/
    restart: always

  frontend:
    build: ./frontend
    expose:
      - "3000"
    restart: always
