name: Production Deployment CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Create .env file
        run: |
          cd frontend
          echo "SUPABASE_PROJECT_URL=${{ secrets.SUPABASE_PROJECT_URL }}" >> .env
          echo "SUPABASE_API_KEY=${{ secrets.SUPABASE_API_KEY }}" >> .env

      - name: Build Docker images with docker-compose
        run: |
          docker-compose -f docker-compose.yml build

      - name: Save Docker images
        run: |
          IMAGES=$(docker-compose -f docker-compose.yml images -q)
          for IMAGE in $IMAGES; do
            docker save $IMAGE -o ${IMAGE//:/_}.tar
          done

      - name: Upload Docker images
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: docker-images.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Docker images
        uses: actions/download-artifact@v2
        with:
          name: docker-images
          path: .

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/gymba-app
            git pull origin master
            docker load -i docker-images.tar
            docker-compose down
            docker image prune -f
            docker-compose up -d
